### ISSUE TITLE
File not found errors crash gulp watch

### ISSUE THREAD

**Issue by redskyburning** [jamesramsay/hercule#49] opened 2015-10-05 19:35 UTC
First off, very helpful library, appreciate the hard work.

Working on documenting a large api using apiary and using hercule to handle various includes to make things a bit more manageable. I've written a simple gulp watcher to monitor changes and dump everything into the main .apib file, and all that works great. The only problem I've found is that when I screw up a file path hercule causes my gulp watcher to hang. I will get an error like 'Error: File (badfilename.md) not found.', and all execution stops. I can manually kill the task, fix the error and restart it, but that's not what I'm looking for. I don't claim to be a gulp expert, but I've tried various ways of error handling, and none have managed to catch the error.

I have found one solution to the problem. If I change the default return statement in readFile() (utils.js) from return null to return '' (empty string), then I will still get the error (which is good), but the task will continue and I can address my mistake without restarting.

So, am I missing something? Is there a best practice for this kind of error handling? Will this modification break something else in hercule that I haven't spotted yet?

**Comment by jamesramsay** [comment] 2015-10-16 00:33
Sorry for the slow response. I'm glad you find hercule useful.

I haven't been using Hercule within a gulp watcher, but I can definitely understand how the problem you're having is annoying. I look into it and see what I can come up with.

My initial inclination is that if a file is referenced, an error should be thrown if it can't be found. But there might be other ways for me to do that.

**Comment by jamesramsay** [comment] 2015-11-10 23:52
@redskyburning this issue should be fixed with Hercule 1.2.2 from #60

**Comment by jamesramsay** [comment] 2015-11-10 23:52
Closed by #60

**Closed by jamesramsay** 2015-11-10 23:52 UTC

**Comment by Ramblurr** [comment] 2016-03-08 19:01
Hey @jamesramsay  and @redskyburning. I'm trying to get hercule integrated into a gulp task so it is a part of our workflow. I'm not too familiar with streams and pipes in node however, could you demo a working gulp task that works with the TranscludeStream?
Following is my attempt, but I think the gulp.src and .dest are operating on different IO types than the transcluder.

```
import gulp from 'gulp';
import { TranscludeStream } from 'hercule';

var mainApib = './src/api.apib';
gulp.task('combine', function() {
  let transcluder = new TranscludeStream();
  gulp.src(mainApib)
    .pipe(transcluder).
    .pipe(gulp.dest('./build/api.apib'));
});
```

**Comment by jamesramsay** [comment] 2016-03-09 02:42
@Ramblurr it seems to be caused by Gulp's special "vinyl" streams which are a bit different to native streams.

The following should would for you

```javascript
import gulp from 'gulp';
import { TranscludeStream } from 'hercule';
import source from 'vinyl-source-stream';

var mainApib = './src/api.apib';
gulp.task('combine', function() {
  let transcluder = new TranscludeStream();
  source(mainApib)
    .pipe(transcluder).
    .pipe(gulp.dest('./build/api.apib'));
});
```

I'll try to put together some notes about using Hercule with Gulp in the next few weeks.

**Comment by jamesramsay** [comment] 2016-03-11 10:48
@Ramblurr I'm adding an example in the PR #192
